name: export-benchmark-results
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Regex filter for benchmark target names that contains the benchmarks to run. If not provided, all targets will be run."
        required: false
        type: string
      filter:
        description: "Regex filter for benchmark names. If not provided, all benchmarks will be run."
        required: false
        type: string
      skip:
        description: "Regex filter for benchmark names to skip. If not provided, no benchmarks will be skipped."
        required: false
        type: string

defaults:
  run:
    shell: bash --noprofile --norc -e -u -o pipefail {0}

jobs:
  export-benchmark-results:
    runs-on: [self-hosted, linux, x64]

    container: swift:6.2-noble

    timeout-minutes: 1440

    steps:
      - name: Install dependencies
        run: |
          apt update -q && apt install -yq libjemalloc-dev zstd

      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Restore .build
        if: ${{ runner.debug != '1' }}
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: Benchmarks/.build
          key: "swiftpm-benchmark-build-${{ runner.os }}-${{ github.sha }}"
          restore-keys: "swiftpm-benchmark-build-${{ runner.os }}-"

      - name: Run benchmarks
        run: |
          COMMAND="swift package -c release \
            --package-path Benchmarks \
            --allow-writing-to-directory="$PWD" \
            benchmark run \
            --format histogram"

          if [[ -n '${{ inputs.target }}' ]]; then
            COMMAND="$COMMAND --target '${{ inputs.target }}'"
          fi

          if [[ -n '${{ inputs.filter }}' ]]; then
            COMMAND="$COMMAND --filter '${{ inputs.filter }}'"
          fi

          if [[ -n '${{ inputs.skip }}' ]]; then
            COMMAND="$COMMAND --skip '${{ inputs.skip }}'"
          fi

          eval "$COMMAND"

      - name: Cache .build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: Benchmarks/.build
          key: "swiftpm-benchmark-build-${{ runner.os }}-${{ github.sha }}"

      - name: Calculate archive file name
        id: calculate-archive-file-name
        run: |
          TIMESTAMP="$(date -u +"%Y-%m-%d-%H-%M-%S")"
          FILE_NAME="swift-dns_benchmark_results_${TIMESTAMP}"

          if [[ -n '${{ inputs.target }}' ]]; then
            TARGET="$(echo '${{ inputs.target }}' | tr ' ' '_')"
            FILE_NAME="${FILE_NAME}_target_${TARGET}"
          fi

          if [[ -n '${{ inputs.filter }}' ]]; then
            FILTER="$(echo '${{ inputs.filter }}' | tr ' ' '_')"
            FILE_NAME="${FILE_NAME}_filter_${FILTER}"
          fi

          if [[ -n '${{ inputs.skip }}' ]]; then
            SKIP="$(echo '${{ inputs.skip }}' | tr ' ' '_')"
            FILE_NAME="${FILE_NAME}_skip_${SKIP}"
          fi

          FILE_NAME="${FILE_NAME}_${{ github.sha }}"

          echo "file_name=${FILE_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Archive benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.calculate-archive-file-name.outputs.file_name }}"
          path: "*.histogram.txt"
