name: nightly-tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize] }
  push: { branches: [main] }
  schedule:
    - cron: "0 6 * * 6"

defaults:
  run:
    shell: bash --noprofile --norc -e -u -o pipefail {0}

jobs:
  linux-nightly-tests:
    strategy:
      fail-fast: false
      matrix:
        swift-image:
          - name: swiftlang/swift:nightly-6.3-jammy
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ubuntu-latest

    container: ${{ matrix.swift-image.name }}

    timeout-minutes: 15

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v6

      - name: Install zstd for faster caching, and curl for codecov action
        run: |
          apt-get update -y
          apt-get install -y zstd curl

      - name: Restore .build
        if: ${{ runner.debug != '1' }}
        id: "restore-cache"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-nightly-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-nightly-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"

      - name: Build ${{ github.event.repository.name }}
        run: |
          # keeping code coverage flag to check for regressions
          swift build \
            --build-tests \
            --enable-code-coverage \
            --explicit-target-dependency-import-check error \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Cache .build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-nightly-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        run: |
          # keeping code coverage flag to check for regressions
          swift test \
            --skip-build \
            --enable-code-coverage \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

  cache-swiftly-toolchain-for-macos:
    strategy:
      fail-fast: false
      matrix:
        swift:
          - version: 6.3-snapshot

    runs-on: macos-26

    timeout-minutes: 20

    env:
      SWIFTLY_HOME_DIR: "/Users/runner/.swiftly"
      SWIFTLY_BIN_DIR: "/Users/runner/.swiftly/bin"
      SWIFTLY_TOOLCHAINS_DIR: "/Users/runner/Library/Developer/Toolchains"

    steps:
      - name: Set today's date
        run: echo "TODAY=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

      - name: Restore swiftly home
        if: ${{ runner.debug != '1' }}
        id: "restore-home"
        uses: actions/cache/restore@v4
        with:
          path: "${{ env.SWIFTLY_HOME_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Restore swiftly bin
        if: ${{ runner.debug != '1' }}
        id: "restore-bin"
        uses: actions/cache/restore@v4
        with:
          path: "${{ env.SWIFTLY_BIN_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Restore swiftly toolchains
        if: ${{ runner.debug != '1' }}
        id: "restore-toolchains"
        uses: actions/cache/restore@v4
        with:
          path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Update swift via Swiftly
        run: |
          # Installation commands from https://www.swift.org/install/macos
          curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          "${SWIFTLY_BIN_DIR}/swiftly" init --assume-yes --skip-install --quiet-shell-followup
          . "${SWIFTLY_HOME_DIR}/env.sh"

          # Update GitHub PATH
          echo "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

          # Update swift
          swiftly install --assume-yes ${{ matrix.swift.version }}
          swiftly use --assume-yes ${{ matrix.swift.version }}

      - name: Cache swiftly home
        if: steps.restore-home.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: "${{ env.SWIFTLY_HOME_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Cache swiftly bin
        if: steps.restore-bin.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: "${{ env.SWIFTLY_BIN_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Cache swiftly toolchains
        if: steps.restore-toolchains.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

  macos-nightly-tests:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - version: macos-15
          - version: macos-26
        xcode:
          - version: latest-stable
        swift:
          - version: 6.3-snapshot
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ${{ matrix.macos.version }}

    needs: cache-swiftly-toolchain-for-macos

    timeout-minutes: 20

    env:
      SWIFTLY_HOME_DIR: "/Users/runner/.swiftly"
      SWIFTLY_BIN_DIR: "/Users/runner/.swiftly/bin"
      SWIFTLY_TOOLCHAINS_DIR: "/Users/runner/Library/Developer/Toolchains"

    steps:
      - name: Setup appropriate Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode.version }}

      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v6

      - name: Set today's date
        run: echo "TODAY=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

      - name: Restore swiftly home
        id: "restore-home"
        uses: actions/cache/restore@v4
        with:
          path: "${{ env.SWIFTLY_HOME_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Restore swiftly bin
        id: "restore-bin"
        uses: actions/cache/restore@v4
        with:
          path: "${{ env.SWIFTLY_BIN_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Restore swiftly toolchains
        id: "restore-toolchains"
        uses: actions/cache/restore@v4
        with:
          path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ env.TODAY }}-${{ runner.os }}"

      - name: Update swift via Swiftly
        run: |
          # Workaround some kind of GitHub caching issue where it struggles to restore or cache the swiftly toolchain
          BLOCK_SIZE="$(du -s '${{ env.SWIFTLY_TOOLCHAINS_DIR }}' | awk '{print $1}')"
          if [[ "${BLOCK_SIZE}" -lt 1024 ]]; then
            echo "Toolchain directory is too small (${BLOCK_SIZE} blocks), deleting all swiftly directories for fresh installation"
            rm -rf '${{ env.SWIFTLY_TOOLCHAINS_DIR }}' '${{ env.SWIFTLY_BIN_DIR }}' '${{ env.SWIFTLY_HOME_DIR }}'
          else
            echo "Toolchain directory is large enough (${BLOCK_SIZE} blocks), will use the restored toolchain"
          fi

          # Installation commands from https://www.swift.org/install/macos
          curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          "${SWIFTLY_BIN_DIR}/swiftly" init --assume-yes --skip-install --quiet-shell-followup
          . "${SWIFTLY_HOME_DIR}/env.sh"

          # Update GitHub PATH
          echo "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

          # Update swift
          swiftly install --assume-yes ${{ matrix.swift.version }}
          swiftly use --assume-yes ${{ matrix.swift.version }}

      - name: Restore .build
        if: ${{ runner.debug != '1' }}
        id: "restore-cache"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-"

      - name: Build ${{ github.event.repository.name }}
        run: |
          swift build \
            --build-tests \
            --enable-code-coverage \
            --explicit-target-dependency-import-check error \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

      - name: Cache .build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        run: |
          # keeping code coverage flag to check for regressions
          swift test \
            --skip-build \
            --enable-code-coverage \
            -Xswiftc -require-explicit-sendable \
            -c ${{ matrix.config.mode }}

  android-nightly-tests:
    strategy:
      fail-fast: false
      matrix:
        swift:
          - version: nightly-6.3
        config:
          - mode: "debug"
          - mode: "release"

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Free disk space for emulator
        run: |
          sudo rm -rf /opt/microsoft /opt/google /opt/az /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/share/chromium /usr/local/share/powershell /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/share/boost
          docker image prune --all --force
          docker builder prune -a

      - name: Ensure zstd is available for faster caching
        run: sudo apt-get update -yq && sudo apt-get install -yq zstd

      - name: Check out code
        uses: actions/checkout@v6

      - name: Replace symlinks with the actual files
        run: find . -type l -exec sh -c 'LINKED="$(readlink -f "{}")"; rm "{}"; cp -a "$LINKED" "{}"' \;

      - name: Run unit tests
        uses: skiptools/swift-android-action@v2
        with:
          android-emulator-test-folder: /data/local/tmp/android-xctest
          test-env: PROJECT_ROOT_FOR_TESTING=/data/local/tmp/android-xctest
          swift-version: ${{ matrix.swift.version }}
          swift-configuration: ${{ matrix.config.mode }}
          copy-files: Tests
          swift-build-flags: >-
            --build-tests
            --explicit-target-dependency-import-check error
          swift-test-flags: --skip "IntegrationTests."
